FROM php:7.3-fpm

RUN apt-get update

RUN docker-php-ext-install pdo_mysql

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y --no-install-recommends nodejs
RUN npm install -g npm

COPY ./ /var/www/html/

RUN php composer.phar install --no-dev
RUN chmod -R a+w storage/ bootstrap/cache

RUN npm install
RUN npm run production

