FROM php:7.3-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
    zip \
    unzip \
    libpq-dev

RUN docker-php-ext-install pdo_mysql pdo_pgsql

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y --no-install-recommends nodejs

COPY ./ /var/www/html/

RUN php composer.phar install --no-dev
RUN chmod -R a+w storage/ bootstrap/cache

RUN npm install
RUN npm run production

